### ISSUE TITLE
I wanna get password from client without echo

### ISSUE THREAD

**Issue by voidest1** [cadpnq/telnetlib#11]
I made a telnet server by telnetlib. 
I wanna get password from client without echo, so I find a function to implement it.
But enableLocal(0x01) can did it, and then I cannot recover it to echo.
`this.socket.enableLocal(0x01);`
if I call following function, then throw an exception.
`this.socket.disableLocal(0x01);`

exception:
`ReferenceError: OptionState is not defined
  at /data/www/zerone/client/node_modules/telnetlib/src/TelnetSocket/TelnetSocket.js:239:14
`

**Comment by voidest1** [comment]
I found the problem, because typo wrong.
change OptionState to optionState should fix it.

**Comment by cadpnq** [comment]
That's embarrassing on my part. I'll see if I can't get a new version out later today.

**Comment by cadpnq** [comment]
I just published 1.0.2 that fixed this (and a few other similar mistakes in the same area).

**Comment by voidest1** [comment]
thanks a lot
